# Generated by Django 3.2.25 on 2024-07-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents_submitted',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
