# Generated by Django 3.2.25 on 2024-07-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20240726_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
