# Generated by Django 3.2.25 on 2024-07-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
