# Generated by Django 3.2.25 on 2024-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_link', models.URLField()),
                ('tags', models.JSONField()),
                ('details', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('application_process', models.TextField()),
                ('documents_required', models.TextField()),
                ('scheme_short_title', models.CharField(max_length=30)),
                ('scheme_category', models.JSONField()),
                ('scheme_sub_category', models.JSONField()),
                ('gender', models.JSONField()),
                ('minority', models.BooleanField(default=False)),
                ('beneficiary_state', models.JSONField(blank=True, null=True)),
                ('residence', models.JSONField()),
                ('caste', models.JSONField()),
                ('disability', models.BooleanField(default=False)),
                ('occupation', models.JSONField(blank=True, null=True)),
                ('marital_status', models.JSONField()),
                ('education', models.JSONField(blank=True, null=True)),
                ('age', models.JSONField()),
                ('is_bpl', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('original_eligibility', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['scheme_name'], name='scheme_mana_scheme__0c40bf_idx'),
        ),
    ]
