# Generated by Django 3.2.25 on 2024-07-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme_manager', '0002_scheme_summary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheme',
            name='scheme_mana_scheme__0c40bf_idx',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
