# Generated by Django 3.2.25 on 2024-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme_manager', '0003_auto_20240720_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme_short_title',
            field=models.CharField(max_length=100),
        ),
    ]
