# Generated by Django 3.2.25 on 2024-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme_manager', '0004_alter_scheme_scheme_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='original_eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
